---
title: Taylor's Barbershop
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    permalink: "/products/:title/"
  uploads:
    title: Uploads
    output: true
email: montier.kess@gmail.com
description: 'Welcome to Taylor’s Barbershop, a hair lounge experience for men, women
  and kids.

'
baseurl: ''
url: ''
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
