---
title: Taylor's Barbershop
timezone: UTC
collections:
  barbers:
    title: Barbers
    output: false
  careers:
    title: Careers
    output: false
  docs:
    title: Docs
    output: false
  faqs:
    title: Faqs
    output: false
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    permalink: "/products/:title/"
  services:
    title: Services
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: barbers
  values:
    avatar: "/assets/img/barber_chandra.jpg"
    name: Chandra B.
    team_position: barber stylist
- scope:
    path: ''
    type: careers
  values:
    career_title: master barber
- scope:
    path: ''
    type: faqs
  values:
    faqs_title: Are children welcomed in Taylor's Barbershop if they are not getting
      a hair cut?
    faqs_text: Yes, children at least 2 years of age and older are welcomed and serviced
      in the barbershop.
- scope:
    path: ''
    type: services
  values:
    title: Taylor's Hair Cut
    price: starting at $25
email: montier.kess@gmail.com
description: 'Welcome to Taylor’s Barbershop, a hair lounge experience for men, women
  and kids.

'
baseurl: ''
url: ''
google_handle: https://www.google.com/maps/place/Taylor's+Barber+Shop/@37.5451205,-77.4441264,17z/data=!4m7!3m6!1s0x0:0xcae4d79a0139e271!8m2!3d37.5451205!4d-77.4419377!9m1!1b1
yelp_handle: https://www.yelp.com/biz/taylors-barbershop-richmond
instagram_handle: taylorsbarbershop
facebook_handle: taylorbarbershoprva
phone: 804-643-1600
book_now: tel:{{ site.phone }}
taylors_job_application: https://taylorsbarbershop.typeform.com/to/fo60ho
keywords: barbershop,mens grooming,grooming,hair cuts,facials,taylors cuts,braids,towel shave,beard trim,taylors kids cuts,mens hair coloring,shampoo,deep conditioning
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
