---
title: Taylor's Barbershop
timezone: UTC
collections:
  docs:
    title: Docs
    output: false
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    permalink: "/products/:title/"
  uploads:
    title: Uploads
    output: true
email: montier.kess@gmail.com
description: 'Welcome to Taylor’s Barbershop, a hair lounge experience for men, women
  and kids.

'
baseurl: ''
url: ''
google_handle: https://www.google.com/maps/place/Taylor's+Barber+Shop/@37.5451205,-77.4441264,17z/data=!4m7!3m6!1s0x0:0xcae4d79a0139e271!8m2!3d37.5451205!4d-77.4419377!9m1!1b1
yelp_handle: https://www.yelp.com/biz/taylors-barbershop-richmond
instagram_handle: taylorsbarbershop
facebook_handle: taylorbarbershoprva
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
